@startuml

package "nfs" {

    class NearFieldScanner {
        - _scanner: Scanner
        - _audio: IAudio
        - _measurement_motion_manager: IMotionManager
        + take_single_measurement()
        + take_measurement_set()
        + shutdown()
    }

    class NearFieldScannerFactory {
        {static} + create(scanner: Scanner, config_file: str): NearFieldScanner
    }

    package "scanner" {
        class Scanner {
            - _grbl_controller: IGrblController
            - _feed_rate: float
            + planar_move_to(r: float, z: float)
            + radial_move_to(r: float)
            + angular_move_to(angle: float)
            + vertical_move_to(z: float)
            + cw_arc_move_to(r: float, z: float, radius: float)
            + ccw_arc_move_to(r: float, z: float, radius: float)
            + get_position(): CylindricalPosition
            + shutdown()
            + home()
        }

        abstract class IMotionManager {
            + {abstract} move_to_safe_starting_radius()
            + {abstract} next(): CylindricalPosition
            + {abstract} ready(): bool
            + {abstract} reset()
            + {abstract} shutdown()
        }

        class CylindricalMeasurementMotionManager
        class SphericalMeasurementMotionManager

        class MotionManagerFactory {
            {static} + create(config_file: str, section: str, scanner: Scanner): IMotionManager
        }

        class ScannerFactory {
            {static} + create(config_file: str): Scanner
        }
    }

    package "grbl_controller" {
        abstract class IGrblController {
            + {abstract} send(message: str)
            + {abstract} send_and_wait_for_move_ready(message: str)
            + {abstract} shutdown()
            + {abstract} get_position(): CylindricalPosition
        }

        class ESP32Duino
        class GrblControllerMock
        class GrblStreamerClientConnection
        class GrblControllerFactory {
            {static} + create(section: str, config_file: str): IGrblController
        }
    }

    package "audio" {
        abstract class IAudio {
            + {abstract} measure_ir(position: CylindricalPosition, order_id: str = "NA")
        }

        class Audio
        class MockInterfaceAudio
        class AudioMock

        class AudioFactory {
            {static} + create(config_file: str, audio_section: str = "audio"): IAudio
        }
    }

    package "measurement_points" {
        interface MeasurementPoints {
            + next(): CylindricalPosition
            + ready(): bool
            + get_radius(): float
            + reset()
            + need_to_do_evasive_move(): bool
        }

        package "plugins" {
            class CylindricalMeasurementPoints
            class FileMeasurementPoints
            class SphericalMeasurementPoints
            class SphericalMeasurementPointsArcs
            class SphericalMeasurementPointsArcsRandom
            class SphericalMeasurementPointsSorted
        }
    }

    package "datatypes" {
        class CylindricalPosition {
            - _r: float
            - _t: float
            - _z: float
            + r(): float
            + t(): float
            + z(): float
            + length(): float
        }
    }
}

NearFieldScanner --> Scanner
NearFieldScanner --> IAudio
NearFieldScanner --> IMotionManager
NearFieldScannerFactory ..> NearFieldScanner

Scanner --> IGrblController
ScannerFactory ..> Scanner

IGrblController <|.. ESP32Duino
IGrblController <|.. GrblControllerMock
ESP32Duino --> GrblStreamerClientConnection
GrblControllerFactory ..> IGrblController

IMotionManager <|.. CylindricalMeasurementMotionManager
IMotionManager <|.. SphericalMeasurementMotionManager
CylindricalMeasurementMotionManager --> MeasurementPoints
SphericalMeasurementMotionManager --> MeasurementPoints
MotionManagerFactory ..> IMotionManager

IAudio <|.. Audio
IAudio <|.. AudioMock
Audio <|-- MockInterfaceAudio
AudioFactory ..> IAudio

MeasurementPoints <|.. CylindricalMeasurementPoints
MeasurementPoints <|.. FileMeasurementPoints
MeasurementPoints <|.. SphericalMeasurementPoints
MeasurementPoints <|.. SphericalMeasurementPointsArcs
MeasurementPoints <|.. SphericalMeasurementPointsArcsRandom
MeasurementPoints <|.. SphericalMeasurementPointsSorted

@enduml