[plugins]
plugin_1 = plugins.cylindrical_measurement_points
plugin_2 = plugins.spherical_measurement_points
plugin_3 = plugins.spherical_measurement_points_sorted
plugin_4 = plugins.spherical_measurement_points_arcs
plugin_5 = plugins.spherical_measurement_points_arcs_random

[mock]
type = Mock

[grbl_streamer]
mock = False
# type = Arduino
baudrate = 115200

[windows]
port = COM5
step_idle_delay = 255  # ms, 255 is always on

[grbl_x_axis]
steps_per_millimeter = 291.008  # 145.504  # 72.752
maximum_rate = 25000  # mm/min
acceleration = 100  # mm/sec^2
invert_direction = False

[grbl_y_axis]
steps_per_millimeter = 291.008  # 145.504  # 72.752
maximum_rate = 25000  # mm/min
acceleration = 100  # mm/sec^2
invert_direction = True

[grbl_rot_axis]
steps_per_millimeter = 2202.66666667  # 177/12/360*64*200*42/10
maximum_rate = 400  # mm/min
acceleration = 2  # mm/sec^2
invert_direction = False

[ESP32DuinoRotation]
type = ESP32DuinoRotation
rotation_mover_controller = fluidnc1
axis = Z

[fluidnc2]
type = ESP32Duino
client_controller = OrangePi  # GrblStreamerClientConnection
grbl_x_axis_config = grbl_x_axis
grbl_y_axis_config = grbl_y_axis

[FileWriterClientConnection]
type = FileWriterClientConnection
file_name = NearFieldScanner.gcode

[GrblStreamerClientConnection]
type = GrblStreamerClientConnection

[OrangePi]
type = WebSocketClientConnection
web_socket = ws://localhost:8001

[RealClientConnectionScanner]
type = WebSocketClientConnection
web_socket = ws://fluidnc2.local:81

[RealClientConnectionRotator]
type = WebSocketClientConnection
web_socket = ws://fluidnc.local:81

[fluidnc1]
type = Mock  # ESP32Duino
client_controller = RealClientConnectionRotator
grbl_x_axis_config = grbl_rot_axis
grbl_y_axis_config = grbl_rot_axis # read, but y axi is not used

[scanner]
controller = dual_controllers

[dual_controllers]
type = DualControllers
rotator = ESP32DuinoRotation  # tic
planar_mover_controller = fluidnc2  # grbl_streamer
feed_rate = 35000

[combined_controller]
type = CombinedController
controller = fluidnc2
feed_rate = 35000

[sweep]
type = ExponentialSweep
sample_rate = 44100  # Hz
minimum_frequency = 20  # Hz
maximum_frequency = 20000  # Hz
duration = 1  # s
padding_time = 1  # s

[audio]
mock = True
device_id = 0

[measurement_points]
type = SphericalMeasurementPointsArcsRandom
nr_of_points = 5000
wall_spacing = 30  # mm
radius = 320  # mm

[motion_manager]
type = CylindricalMeasurementMotionManager